"""Roma's fare model and its three data-provenance levels.

The model is deterministic: the same question asked twice gets the same answer,
and the same question asked "as of" an earlier date reproduces what Roma would
have quoted then. That is what makes the price history internally consistent and
the buy/wait rules meaningful.

None of it is a market price. Every number this module produces is labelled
``simulated``.
"""

from __future__ import annotations

import hashlib
from datetime import date

from . import airlines, airports
from .models import SearchRequest

# --- The three data levels every price Roma shows is tagged with -------------
LEVEL_LIVE = "live_provider"
LEVEL_HISTORY = "modeled_from_history"
LEVEL_SIMULATED = "simulated"

DATA_LEVELS: dict[str, dict[str, str]] = {
    LEVEL_LIVE: {
        "id": LEVEL_LIVE,
        "label": "Live provider fare",
        "short": "Live",
        "detail": "Returned by a connected fare provider for this exact query.",
    },
    LEVEL_HISTORY: {
        "id": LEVEL_HISTORY,
        "label": "Modelled from recorded history",
        "short": "From history",
        "detail": "Derived from prices Roma recorded for this route on earlier days.",
    },
    LEVEL_SIMULATED: {
        "id": LEVEL_SIMULATED,
        "label": "Simulated estimate",
        "short": "Simulated",
        "detail": "Generated by Roma's own fare model. Not a market price and not bookable.",
    },
}

CABIN_MULTIPLIERS: dict[str, float] = {
    "economy": 1.0,
    "premium_economy": 1.78,
    "business": 3.40,
    "first": 5.60,
}

# Month-of-departure demand, index 1..12. A modelling assumption.
_MONTH_INDEX: dict[int, float] = {
    1: 0.92,
    2: 0.90,
    3: 0.98,
    4: 1.02,
    5: 1.05,
    6: 1.14,
    7: 1.20,
    8: 1.16,
    9: 0.99,
    10: 1.01,
    11: 1.04,
    12: 1.18,
}

# Monday=0 .. Sunday=6, applied to the outbound date.
_WEEKDAY_INDEX: tuple[float, ...] = (0.97, 0.95, 0.95, 0.99, 1.06, 1.03, 1.05)


def _seed(*parts: str) -> int:
    digest = hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()
    return int(digest[:12], 16)


def _jitter(seed: int, spread: float) -> float:
    """Stable pseudo-random multiplier in ``1 +/- spread``."""
    unit = (seed % 10_000) / 10_000.0
    return 1.0 + (unit * 2 - 1) * spread


def _distance_base(km: float) -> float:
    """Base one-way economy fare from distance, with the usual taper."""
    if km <= 0:
        return 120.0
    if km < 800:
        return 58.0 + km * 0.140
    if km < 2400:
        return 92.0 + km * 0.086
    if km < 6000:
        return 168.0 + km * 0.058
    if km < 10000:
        return 292.0 + km * 0.041
    return 402.0 + km * 0.032


def _advance_purchase_index(days_out: int) -> float:
    """Cheapest in the 6-12 week window, sharply worse inside two weeks."""
    if days_out < 0:
        return 1.60
    if days_out <= 3:
        return 1.62
    if days_out <= 7:
        return 1.44
    if days_out <= 14:
        return 1.26
    if days_out <= 21:
        return 1.12
    if days_out <= 35:
        return 1.03
    if days_out <= 60:
        return 0.96
    if days_out <= 90:
        return 0.94
    if days_out <= 150:
        return 1.00
    if days_out <= 240:
        return 1.06
    return 1.10


def _trip_length_index(nights: int | None) -> float:
    """One-ways and very short round trips price worse per trip."""
    if nights is None:
        return 0.72
    if nights <= 1:
        return 1.16
    if nights <= 3:
        return 1.06
    if nights <= 6:
        return 1.00
    if nights <= 14:
        return 0.96
    if nights <= 30:
        return 1.01
    return 1.08


def _stop_index(stops: int) -> float:
    return {0: 1.14, 1: 1.00, 2: 0.90}.get(stops, 0.88)


def model_price(
    request: SearchRequest,
    airline_code: str | None,
    *,
    as_of: date,
    stops: int = 1,
    variant: int = 0,
) -> float:
    """The single source of every simulated number Roma quotes.

    ``as_of`` is the date the price is imagined to have been quoted on, which is
    what lets the history backfill reproduce a consistent past.
    """
    km = airports.distance_km(request.origin, request.destination)
    price = _distance_base(km)
    if request.round_trip:
        price *= 2.0
    price *= CABIN_MULTIPLIERS.get(request.cabin, 1.0)
    price *= _MONTH_INDEX.get(request.depart_date.month, 1.0)
    price *= _WEEKDAY_INDEX[request.depart_date.weekday()]
    price *= _advance_purchase_index((request.depart_date - as_of).days)
    price *= _trip_length_index(request.trip_nights)
    price *= _stop_index(stops)
    price *= airlines.price_index(airline_code)

    route_seed = _seed(request.origin, request.destination, str(airline_code), request.cabin)
    price *= _jitter(route_seed, 0.06)
    day_seed = _seed(request.cache_key(), as_of.isoformat(), str(variant))
    price *= _jitter(day_seed, 0.045)

    price *= max(1, request.adults)
    return round(price, 2)


def _duration_minutes(km: float, stops: int, seed: int) -> int:
    cruise = 780.0  # km/h, block-average rather than airspeed
    base = 35 + (km / cruise) * 60
    base += stops * (75 + (seed % 55))
    return int(round(base))


def _candidate_airlines(request: SearchRequest) -> list[str]:
    """A plausible carrier shortlist for a route when none was requested."""
    km = airports.distance_km(request.origin, request.destination)
    long_haul = km > 4000
    origin = airports.get(request.origin)
    destination = airports.get(request.destination)
    regions = _regions_for(
        origin.country if origin else "",
        destination.country if destination else "",
    )
    pool = sorted(
        code
        for code, a in airlines.AIRLINES.items()
        if (a.long_haul or not long_haul) and a.region in regions
    )
    if not pool:
        pool = sorted(
            code for code, a in airlines.AIRLINES.items() if a.long_haul or not long_haul
        )
    seed = _seed(request.origin, request.destination, "carriers")
    offset = seed % len(pool)
    return (pool[offset:] + pool[:offset])[:4]


_COUNTRY_REGION: dict[str, str] = {
    "United States": "North America",
    "Canada": "North America",
    "Mexico": "Latin America",
    "Brazil": "Latin America",
    "Argentina": "Latin America",
    "Chile": "Latin America",
    "Peru": "Latin America",
    "Colombia": "Latin America",
    "Panama": "Latin America",
    "Costa Rica": "Latin America",
    "Ecuador": "Latin America",
    "Uruguay": "Latin America",
}


def _regions_for(origin_country: str, destination_country: str) -> set[str]:
    regions: set[str] = set()
    for country in (origin_country, destination_country):
        regions.add(_COUNTRY_REGION.get(country, ""))
    known = {a.region for a in airlines.AIRLINES.values()}
    resolved = {r for r in regions if r in known}
    return resolved or known


def build_offers(
    request: SearchRequest,
    *,
    as_of: date,
    currency: str,
    requested_airline: str | None,
    requested_airline_label: str | None,
) -> list[dict]:
    """Simulated offers for a request, cheapest first, each level-labelled."""
    km = airports.distance_km(request.origin, request.destination)
    offers: list[dict] = []
    if requested_airline:
        candidates: list[str | None] = [requested_airline]
    elif requested_airline_label:
        # The user asked for a carrier Roma has no record of ("Other").
        candidates = [None]
    else:
        candidates = list(_candidate_airlines(request))
    shapes = [0, 1, 2] if km > 6000 else [0, 1]
    variant = 0
    for code in candidates:
        for stops in shapes:
            variant += 1
            seed = _seed(request.cache_key(), str(code), str(stops))
            price = model_price(request, code, as_of=as_of, stops=stops, variant=variant)
            outbound = _duration_minutes(km, stops, seed)
            inbound = _duration_minutes(km, stops, seed + 7) if request.round_trip else None
            name = airlines.display_name(code, requested_airline_label)
            offers.append(
                {
                    "airline_code": code or "\u2014",
                    "airline_name": name,
                    "price": price,
                    "currency": currency,
                    "stops": stops,
                    "outbound_duration_minutes": outbound,
                    "return_duration_minutes": inbound,
                    "fare_basis": "Refundable" if stops == 0 and price > 900 else "Non-refundable",
                    "provider": "simulated",
                    "data_level": LEVEL_SIMULATED,
                    "notes": (
                        []
                        if code
                        else [
                            "Roma has no reference data for this carrier, so it is priced "
                            "with a neutral airline index."
                        ]
                    ),
                }
            )
    offers.sort(key=lambda offer: offer["price"])
    return offers[:6]
